example_app_8/urls.py
"""
Urls for Example App 8.
"""

from django.conf.urls import url

from . import views


app_name = 'example_app_8'
urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^category/search/$', views.category_search, name='category_search'),
    url(r'^category/create/$', views.category_create, name='category_create'),
    url(r'^category/edit/category_pk/$', views.category_edit, name='category_edit_js'),
    url(r'^category/edit/(?P<pk>[0-9]+)/$', views.category_edit, name='category_edit'),
]

settings/urls.py
"""
Core project Urls.
"""

from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    # Admin Views.
    url(r'^admin/', admin.site.urls),

    # Example App 1 Views.
    url(r'^ex1/', include('example_app_1.urls')),

    # Example App 2 Views.
    url(r'^ex2/', include('example_app_2.urls')),

    # Example App 3 Views.
    url(r'^ex3/', include('example_app_3.urls')),

    # Example App 4 Views.
    url(r'^ex4/', include('example_app_4.urls')),

    # Example App 5 Views.
    url(r'^ex5/', include('example_app_5.urls')),

    # Example App 6 Views.
    url(r'^ex6/', include('example_app_6.urls')),

    # Example App 7 Views.
    url(r'^ex7/', include('example_app_7.urls')),

    # Example App 8 Views.
    url(r'^ex8/', include('example_app_8.urls')),
]

example_app_8/models.py
"""
Models for Example_App_8.
"""

from django.db import models
from django.urls import reverse


class Category(models.Model):
    # Model fields.
    title = models.CharField(max_length=200)
    ## Self-setting/Non-user-editable fields.
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return '{0}'.format(self.title)

    def get_absolute_url(self):
        return reverse('example_app_8:category_edit', kwargs={
            'pk': self.pk,
        })

    def save(self, *args, **kwargs):
        """
        Modify model save behavior.
        """
        # Save model.
        self.full_clean()
        super(Category, self).save(*args, **kwargs)

example_app_8/forms.py
"""
Forms for Example_App_8.
"""

from django import forms

from . import models


class CategoryForm(forms.ModelForm):
    """
    Form view for Category model.
    """
    class Meta:
        model = models.Category
        fields = {
            'title',
        }

example_app_8/views.py
"""
Views for example app 8.
"""

from django.core import serializers
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from . import forms, models


def index(request):
    """
    Index view.
    """
    # Send to template for user display.
    return render(request, 'example_app_8/index.html')


def category_search(request):
    """
    A view showcasing the use of Django models through react.
    """
    # Pull models from database.
    categories = models.Category.objects.all()

    # Convert to json format for React.
    json_categories = serializers.serialize(
        'json',
        categories,
        fields=('title', 'date_created', 'date_modified', 'url')
    )

    # Send to template for user display.
    return render(request, 'example_app_8/category_search.html', {
        'categories': categories,
        'json_categories': json_categories,
    })


def category_create(request):
    """
    Form view for creating a new Category.
    """
    form = forms.CategoryForm()

    # Check if request is post.
    if request.method == 'POST':
        form = forms.CategoryForm(request.POST)
        if form.is_valid():
            category = form.save()

            # Render response for user.
            return HttpResponseRedirect(reverse('example_app_8:category_search'))

    # Handle for non-post request.
    return render(request, 'example_app_8/category_form.html', {
        'form': form,
    })


def category_edit(request, pk):
    """
    Form view for editing a Category.
    """
    category = get_object_or_404(models.Category, pk=pk)
    form = forms.CategoryForm(instance=category)

    # Check if request is post.
    if request.method == 'POST':
        form = forms.CategoryForm(instance=category, data=request.POST)
        if form.is_valid():
            form.save()

            # Render response for user.
            return HttpResponseRedirect(reverse('example_app_8:category_search'))

    # Send to template for user display.
    return render(request, 'example_app_8/category_form.html', {
        'form': form,
        'category': category,
    })

example_app_8/templates/example_app_8/category_form.html
<!doctype html>
{% load staticfiles %}
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://unpkg.com/react@16/umd/react.development.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js" crossorigin></script>
  </head>

  <body>
    <main>
      <h1>Category Form</h1>

      <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
      </form>
    </main>
  </body>

</html>

example_app_8/templates/example_app_8/category_search.html
<!doctype html>
{% load staticfiles %}
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js" crossorigin></script>
  </head>

  <body>
    <main>
      <h1>Django Example App 8</h1>
      <p><a href="{% url 'example_app_8:index' %}">Index</a></p>
      <p><a href="{% url 'example_app_8:category_create' %}">New Category</a></p>
      <hr>
      <div id="vue-root">
        <div v-if="query">
          <label>Search Categories: </label><input v-model="search_value" type="text" placeholder="Search for...">
          <h2>Categories</h2>
          <ul>
            <category
              v-for="category in query"
              v-bind:category="category"
              v-bind:key="category.pk"
            >
            </category>
          </ul>
        </div>
        <div v-else>
          <h2>Something went wrong.</h2>
          <p>If you see this, then Vue did not load properly.</p>
        </div>
      </div>
    </main>

    <script>
      // Get json list of django models as JavaScript variable.
      var categories = {{ json_categories|safe }};

      // Iterate through list of models and save url field for each.
      // This is accomplished by creating a "dummy" url in django to load from. It gets the desired url, but with a
      // placeholder string for the pk (make sure the placeholder is not a valid pk).
      // From here, we use javascript to read the json model information, and replace the dummy url with a valid one.
      // Finally, we add this url to the list of json model information.
      categories.forEach((category) => {
        category.fields['url'] = "{% url 'example_app_8:category_edit_js' %}".replace("category_pk", category.pk)
      });
    </script>
    <script src="{% static 'example_app_8/js/category_search.js' %}"></script>
  </body>

</html>

example_app_8/templates/example_app_8/index.html
<!doctype html>
{% load staticfiles %}
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js" crossorigin></script>
  </head>

  <body>
    <main>
      <h1>Django Example App 8</h1>
      <p><a href="{% url 'example_app_8:category_search' %}">Django models and Vue</a></p>
      <p>This app shows rendering of a Django template with Vue.</p>
      <p>The Vue javascript file can be found within the "static" folder of this app.</p>
      <br>
      <p>Everything below the line is rendered with Vue.</p>
      <hr>
      <div id="vue-root">
        <div v-if="hello_world_header"><h2>{ hello_world_header }</h2></div>
        <div v-else>
          <h2>Something went wrong.</h2>
          <p>If you see this, then Vue did not load properly.</p>
        </div>
      </div>
    </main>

    <script src="{% static 'example_app_8/js/vue_example.js' %}"></script>
  </body>

</html>