example_app_3/urls.py
"""
Urls for Example App 3.
"""

from django.conf.urls import url

from . import views


app_name = 'example_app_3'
urlpatterns = [
    url(r'^$', views.index, name='index'),

    # Overview Views.
    url(r'^address/$', views.address_overview, name='address_overview'),
    url(r'^customer/$', views.customer_overview, name='customer_overview'),

    # Detail Views.
    url(r'^address/detail/(?P<pk>[0-9]+)/$', views.address_detail, name='address_detail'),
    url(r'^customer/detail/(?P<pk>[0-9]+)/$', views.customer_detail, name='customer_detail'),

    # Create Views.
    url(r'^address/create/$', views.address_create, name='address_create'),
    url(r'^customer/create/$', views.customer_create, name='customer_create'),

    # Edit Views.
    url(r'^address/edit/(?P<pk>[0-9]+)/$', views.address_edit, name='address_edit'),
    url(r'^customer/edit/(?P<pk>[0-9]+)/$', views.customer_edit, name='customer_edit'),
]

settings/urls.py
"""
Core project Urls.
"""

from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    # Admin Views.
    url(r'^admin/', admin.site.urls),

    # Example App 1 Views.
    url(r'^ex1/', include('example_app_1.urls')),

    # Example App 2 Views.
    url(r'^ex2/', include('example_app_2.urls')),

    # Example App 3 Views.
    url(r'^ex3/', include('example_app_3.urls')),

    # Example App 4 Views.
    url(r'^ex4/', include('example_app_4.urls')),

    # Example App 5 Views.
    url(r'^ex5/', include('example_app_5.urls')),

    # Example App 6 Views.
    url(r'^ex6/', include('example_app_6.urls')),

    # Example App 7 Views.
    url(r'^ex7/', include('example_app_7.urls')),

    # Example App 8 Views.
    url(r'^ex8/', include('example_app_8.urls')),
]

example_app_3/models.py
"""
Models for Example App 3.
"""

from django.db import models


MAX_LENGTH = 200


class Address(models.Model):
    """
    An address model for a customer.
    """
    # Model Fields.
    address = models.CharField(max_length=MAX_LENGTH)
    # Self-setting/Non-user-editable fields.
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Address'
        verbose_name_plural = 'Addresses'

    def __str__(self):
        return '{0}'.format(self.address)

    def clean(self, *args, **kwargs):
        """
        Custom cleaning implementation. Includes validation, setting fields, etc.
        """
        # Nothing to put here for the moment.

    def save(self, *args, **kwargs):
        """
        Modify model save behavior.
        """
        # Save model.
        self.full_clean()
        super(Address, self).save(*args, **kwargs)


class Customer(models.Model):
    """
    A customer model.
    """
    # Relational fields.
    address = models.ForeignKey('Address', on_delete=models.CASCADE, blank=True, null=True)
    # Model Fields.
    first_name = models.CharField(max_length=MAX_LENGTH)
    last_name = models.CharField(max_length=MAX_LENGTH)
    # Self-setting/Non-user-editable fields.
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Customer'
        verbose_name_plural = 'Customers'

    def __str__(self):
        return '{0} {1}, {2}'.format(self.first_name, self.last_name, self.address)

    def clean(self, *args, **kwargs):
        """
        Custom cleaning implementation. Includes validation, setting fields, etc.
        """
        # Nothing to put here for the moment.

    def save(self, *args, **kwargs):
        """
        Modify model save behavior.
        """
        # Save model.
        self.full_clean()
        super(Customer, self).save(*args, **kwargs)

    def get_full_name(self):
        return self.first_name + ' ' + self.last_name

example_app_3/forms.py
"""
Forms for Example App 3.
"""

from django import forms

from . import models


#region Admin Form Views

class AddressAdminForm(forms.ModelForm):
    """
    Define admin form view for Address model.
    """
    class Meta:
        model = models.Address
        # Define all fields which you wish to have displayed.
        # Note that this is not necessarily the order displayed. It just determines what is displayed at all.
        # Useful if you want hidden/automatically-updating fields to hold metadata within a model.
        fields = {
            'address',
        }
        # Define all custom error messages, such as example.
        # Note that Django should automatically create a error message for max_length.
        # This example overrides the default.
        error_messages = {
            'address': {
                'max_length': 'Field is too long. Must be less than 200 characters.'
            }
        }


class CustomerAdminForm(forms.ModelForm):
    """
    Define admin form view for Customer model.
    """
    class Meta:
        model = models.Customer
        fields = {
            'address',
            'first_name',
            'last_name',
        }
        # Change what a field is displayed as in the admin front end view.
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
        }


#endregion Admin Form Views



#region Standard Form Views

class AddressForm(forms.ModelForm):
    """
    Define standard form view for Address model.
    """
    class Meta:
        model = models.Address
        fields = {
            'address',
        }


class CustomerForm(forms.ModelForm):
    """
    Define standard form view for Customer model.
    """
    class Meta:
        model = models.Customer
        fields = {
            'address',
            'first_name',
            'last_name',
        }

#endregion Standard Form Views

example_app_3/views.py
"""
Views for Example App 3.
"""

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from . import forms, models


def index(request):
    """
    Index view.
    """
    # Send to template for user display.
    return render(request, 'example_app_3/index.html')


#region Overview Views

def address_overview(request):
    """
    List view for Address model.
    """
    # Pull models from database.
    address_list = models.Address.objects.all()

    # Send to template for user display.
    return render(request, 'example_app_3/address_overview.html', {
        'address_list': address_list,
    })


def customer_overview(request):
    """
    List view for Customer model.
    """
    # Pull models from database.
    customer_list = models.Customer.objects.all()

    # Send to template for user display.
    return render(request, 'example_app_3/customer_overview.html', {
        'customer_list': customer_list,
    })

#endregion Overview Views


#region Detail Views

def address_detail(request, pk):
    """
    Displays details of the given address.
    """
    # Pull models from database.
    address = get_object_or_404(models.Address, pk=pk)

    # Send to template for user display.
    return render(request, 'example_app_3/address_detail.html', {
        'address': address,
    })


def customer_detail(request, pk):
    """
    Displays details of the given customer.
    """
    # Pull models from database.
    customer = get_object_or_404(models.Customer, pk=pk)

    # Send to template for user display.
    return render(request, 'example_app_3/customer_detail.html', {
        'customer': customer,
    })

#endregion Detail Views


#region Create Views

def address_create(request):
    """
    Form view for creating a new Address.
    """
    form = forms.AddressForm()

    # Check if request is post.
    if request.method == 'POST':
        form = forms.AddressForm(request.POST)
        if form.is_valid():
            address = form.save()

            # Render response for user.
            return HttpResponseRedirect(reverse('example_app_3:address_detail', args=(address.pk, )))

    # Handle for non-post request.
    return render(request, 'example_app_3/forms/address.html', {
        'form': form,
    })


def customer_create(request):
    """
    Form view for creating a new Customer.
    """
    form = forms.CustomerForm()

    # Check if request is post.
    if request.method == 'POST':
        form = forms.CustomerForm(request.POST)
        if form.is_valid():
            customer = form.save()

            # Render response for user.
            return HttpResponseRedirect(reverse('example_app_3:customer_detail', args=(customer.pk, )))

    # Handle for non-post request.
    return render(request, 'example_app_3/forms/customer.html', {
        'form': form,
    })

#endregion Create Views


#region Edit Views

def address_edit(request, pk):
    """
    Form view for editing a Address.
    """
    # Pull models from database.
    address = get_object_or_404(models.Address, pk=pk)
    form = forms.AddressForm(instance=address)

    # Check if request is post.
    if request.method == 'POST':
        form = forms.AddressForm(instance=address, data=request.POST)
        if form.is_valid():
            form.save()

            # Render response for user.
            return HttpResponseRedirect(reverse('example_app_3:address_detail', args=(address.pk, )))

    # Send to template for user display.
    return render(request, 'example_app_3/forms/address.html', {
        'form': form,
        'address': address,
    })


def customer_edit(request, pk):
    """
    Form view for editing a Customer.
    """
    # Pull models from database.
    customer = get_object_or_404(models.Customer, pk=pk)
    form = forms.CustomerForm(instance=customer)

    # Check if request is post.
    if request.method == 'POST':
        form = forms.CustomerForm(instance=customer, data=request.POST)
        if form.is_valid():
            form.save()

            # Render response for user.
            return HttpResponseRedirect(reverse('example_app_3:customer_detail', args=(customer.pk, )))

    # Send to template for user display.
    return render(request, 'example_app_3/forms/customer.html', {
        'form': form,
        'customer': customer,
    })

#endregion Edit Views

example_app_3/templates/example_app_3/address_base.html
{% extends 'example_app_3/base.html' %}


{% block title %}<title>Address | {% block sub_title %}{% endblock sub_title %}</title>{% endblock title %}


{% block content %}{% endblock content %}

example_app_3/templates/example_app_3/address_detail.html
{% extends 'example_app_3/address_base.html' %}


{% block sub_title %}Detail{% endblock sub_title %}


{% block content %}
  <h1>Address Detail</h1>

  <p>Address: {{ address.address }}</p>
  <p>Created At: {{ address.date_created }}</p>
  <p>Last Updated: {{ address.date_modified }}</p>

  <p><a href="{% url 'example_app_3:address_edit' pk=address.pk %}">Edit</a></p>
{% endblock content %}

example_app_3/templates/example_app_3/address_overview.html
{% extends 'example_app_3/address_base.html' %}


{% block sub_title %}Overview{% endblock sub_title %}


{% block content %}
  <p><a href="{% url 'example_app_3:address_create' %}">New</a></p>

  {% for address in address_list %}
    <li>
      <a href="{% url 'example_app_3:address_detail' pk=address.pk %}">{{ address.address }}</a>
    </li>
  {% endfor %}
{% endblock content %}

example_app_3/templates/example_app_3/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">

  {% block head %}
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      {% block title %}{% endblock title %}

      {% block fonts %}{% endblock fonts %}

      {% block styles %}{% endblock styles %}

      {% block base_scripts %}{% endblock base_scripts %}
    </head>
  {% endblock head %}

  {% block body %}
    <body>
      {% block header %}{% endblock header %}

      <main>{% block content %}{% endblock content %}</main>

      {% block footer %}{% endblock footer %}

      {% block extra_scripts %}{% endblock extra_scripts %}
    </body>
  {% endblock body %}

</html>

example_app_3/templates/example_app_3/customer_base.html
{% extends 'example_app_3/base.html' %}


{% block title %}<title>Customer | {% block sub_title %}{% endblock sub_title %}</title>{% endblock title %}


{% block content %}{% endblock content %}

example_app_3/templates/example_app_3/customer_detail.html
{% extends 'example_app_3/customer_base.html' %}


{% block sub_title %}Detail{% endblock sub_title %}


{% block content %}
  <h1>Customer Detail</h1>

  <p>First Name: {{ customer.first_name }}</p>
  <p>Last Name: {{ customer.last_name }}</p>
  <p>Address: {{ customer.address }}</p>
  <p>Created At: {{ customer.date_created }}</p>
  <p>Last Updated: {{ customer.date_modified }}</p>

  <p><a href="{% url 'example_app_3:customer_edit' pk=customer.pk %}">Edit</a></p>
{% endblock content %}

example_app_3/templates/example_app_3/customer_overview.html
{% extends 'example_app_3/customer_base.html' %}


{% block sub_title %}Overview{% endblock sub_title %}


{% block content %}
  <p><a href="{% url 'example_app_3:customer_create' %}">New</a></p>

  {% for customer in customer_list %}
    <li>
      <a href="{% url 'example_app_3:customer_detail' pk=customer.pk %}">{{ customer.first_name }} {{customer.last_name }}</a>
    </li>
  {% endfor %}
{% endblock content %}

example_app_3/templates/example_app_3/index.html
{% extends 'example_app_3/base.html' %}


{% block title%}<title>Example App 3 Index</title>{% endblock title %}


{% block content %}
  <h1>Example App 3 Index</h1>

  <p><a href="{% url 'example_app_3:address_overview' %}">Addresses</a></p>
  <p><a href="{% url 'example_app_3:customer_overview' %}">Customers</a></p>
{% endblock content %}