example_app_4/urls.py
"""
Urls for Example App 4.
"""

from django.conf.urls import url

from . import views


app_name = 'example_app_4'
urlpatterns = [
    url(r'^$', views.index, name='index'),

    # Overview Views.
    url(r'^topping/$', views.topping_overview, name='topping_overview'),
    url(r'^pizza/$', views.pizza_overview, name='pizza_overview'),

    # Detail Views.
    url(r'^topping/detail/(?P<pk>[0-9]+)/$', views.topping_detail, name='topping_detail'),
    url(r'^pizza/detail/(?P<pk>[0-9]+)/$', views.pizza_detail, name='pizza_detail'),

    # Create Views.
    url(r'^topping/create/$', views.topping_create, name='topping_create'),
    url(r'^pizza/create/$', views.pizza_create, name='pizza_create'),

    # Edit Views.
    url(r'^topping/edit/(?P<pk>[0-9]+)/$', views.topping_edit, name='topping_edit'),
    url(r'^pizza/edit/(?P<pk>[0-9]+)/$', views.pizza_edit, name='pizza_edit'),
]

settings/urls.py
"""
Core project Urls.
"""

from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    # Admin Views.
    url(r'^admin/', admin.site.urls),

    # Example App 1 Views.
    url(r'^ex1/', include('example_app_1.urls')),

    # Example App 2 Views.
    url(r'^ex2/', include('example_app_2.urls')),

    # Example App 3 Views.
    url(r'^ex3/', include('example_app_3.urls')),

    # Example App 4 Views.
    url(r'^ex4/', include('example_app_4.urls')),

    # Example App 5 Views.
    url(r'^ex5/', include('example_app_5.urls')),

    # Example App 6 Views.
    url(r'^ex6/', include('example_app_6.urls')),

    # Example App 7 Views.
    url(r'^ex7/', include('example_app_7.urls')),

    # Example App 8 Views.
    url(r'^ex8/', include('example_app_8.urls')),
]

example_app_4/models.py
"""
Models for Example App 4.
"""

from django.db import models


MAX_LENGTH = 200


class Topping(models.Model):
    """
    A pizza topping model.
    """
    # Model fields
    name = models.CharField(max_length=MAX_LENGTH, unique=True)
    # Self-setting/Non-user-editable fields.
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Topping'
        verbose_name_plural = 'Toppings'

    def __str__(self):
        return '{0}'.format(self.name)

    def clean(self, *args, **kwargs):
        """
        Custom cleaning implementation. Includes validation, setting fields, etc.
        """

    def save(self, *args, **kwargs):
        """
        Modify model save behavior.
        """
        # Save model.
        self.full_clean()
        super(Topping, self).save(*args, **kwargs)


class Pizza(models.Model):
    """
    A pizza model.
    """
    # Relational fields.
    toppings = models.ManyToManyField('Topping', blank=True)
    # Model fields.
    name = models.CharField(max_length=MAX_LENGTH, default='Custom')
    # Self-setting/Non-user-editable fields.
    price = models.DecimalField(max_digits=6, decimal_places=2, default=8)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Pizza'
        verbose_name_plural = 'Pizzas'

    def __str__(self):
        toppings_on_pizza = self.toppings.all()
        return '{0}: {1}'.format(self.name, list(toppings_on_pizza))

    def clean(self, *args, **kwargs):
        """
        Custom cleaning implementation. Includes validation, setting fields, etc.
        """
        # Automatically calculate pizza price on save.
        # Note: To ensure consistency, that means that pizza.save() should always be called whenever a topping
        # many-to-many relationship is created.
        self.get_price()

    def save(self, *args, **kwargs):
        """
        Modify model save behavior.
        """
        # Save model.
        self.full_clean()
        super(Pizza, self).save(*args, **kwargs)

    def get_price(self):
        """
        Determines price. Will be $8 base plus $1.25 per standard topping and another $0.50 for extra topping.
        """
        # Cannot call a relationship query if self is not saved in database first (aka, pk is not defined).
        # Check for this first. If no pk, then it's impossible to have associated toppings yet so default to base price.
        if self.pk is not None:
            self.price = 8
            # Grab the full Many-to-Many relationship model so we can access the additional fields.
            toppings_on_pizza = self.toppings.all()
            # Iterate through the returned queryset. Each one is a single topping for this pizza.
            for relationship in toppings_on_pizza:
                self.price += 1.25
        else:
            self.price = 8

example_app_4/forms.py
"""
Form views for Example App 4.
"""

from django import forms

from . import models


#region Admin Form Views

class ToppingAdminForm(forms.ModelForm):
    """
    Define admin form view for Topping model.
    """
    class Meta:
        model = models.Topping
        fields = {
            'name',
        }


class PizzaAdminForm(forms.ModelForm):
    """
    Define admin form view for Pizza model.
    """
    class Meta:
        model = models.Pizza
        fields = {
            'name',
            'price',
            'toppings',
        }

#endregion Admin Form Views


#region Standard Form Views

class ToppingForm(forms.ModelForm):
    """
    Define admin form view for Topping model.
    """
    class Meta:
        model = models.Topping
        fields = {
            'name',
        }


class PizzaForm(forms.ModelForm):
    """
    Define admin form view for Pizza model.
    """
    def __init__(self, *args, **kwargs):
        super(PizzaForm, self).__init__(*args, **kwargs)
        self.fields['toppings'].widget = forms.widgets.CheckboxSelectMultiple()
        self.fields['toppings'].queryset = models.Topping.objects.all()

    class Meta:
        model = models.Pizza
        fields = {
            'name',
            'toppings',
        }

#endregion Standard Form Views

example_app_2/views.py
"""
Views for Example App 2.
"""

from django.views import generic

from . import forms, models


class IndexView(generic.ListView):
    """
    Index view. Displays all current category models.
    """
    template_name = 'example_app_2/index.html'

    def get_queryset(self):
        # You don't need to define what the list will be called in the template.
        # By returning a model, Django automatically uses "'model_name'_list" as the return.
        # So in this instance, it will be "category_list" by default.
        return models.Category.objects.all()


class DetailView(generic.DetailView):
    """
    Displays details of the given category.
    """
    model = models.Category
    template_name = 'example_app_2/category_detail.html'


class CategoryCreate(generic.edit.CreateView):
    """
    Form view for creating a new Category.
    """
    model = models.Category
    form_class = forms.CategoryForm
    template_name = "example_app_2/forms/category.html"


class CategoryUpdate(generic.edit.UpdateView):
    """
    Form view for editing a Category.
    """
    model = models.Category
    form_class = forms.CategoryForm
    template_name = "example_app_2/forms/category.html"

example_app_4/views.py
"""
Views for Example App 4.
"""

from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from . import forms, models


def index(request):
    """
    Index view.
    """
    # Send to template for user display.
    return render(request, 'example_app_4/index.html')


#region Overview Views

def topping_overview(request):
    """
    List view for Topping model.
    """
    # Pull models from database.
    topping_list = models.Topping.objects.all()

    # Send to template for user display.
    return render(request, 'example_app_4/topping_overview.html', {
        'topping_list': topping_list,
    })


def pizza_overview(request):
    """
    List view for Pizza model.
    """
    # Pull models from database.
    pizza_list = models.Pizza.objects.all()

    # Send to template for user display.
    return render(request, 'example_app_4/pizza_overview.html', {
        'pizza_list': pizza_list,
    })

#endregion Overview Views


#region Detail Views

def topping_detail(request, pk):
    """
    Displays details of the given Topping.
    """
    # Pull models from database.
    topping = get_object_or_404(models.Topping, pk=pk)

    # Send to template for user display.
    return render(request, 'example_app_4/topping_detail.html', {
        'topping': topping,
    })


def pizza_detail(request, pk):
    pizza = get_object_or_404(models.Pizza, pk=pk)
    topping_set = pizza.toppings.all()

    return render(request, 'example_app_4/pizza_detail.html', {
        'pizza': pizza,
        'topping_set': topping_set,
    })

#endregion Detail Views


#region Create Views

def topping_create(request):
    """
    Form view for creating a new Topping.
    """
    form = forms.ToppingForm()

    # Check if request is post.
    if request.method == 'POST':
        form = forms.ToppingForm(request.POST)
        if form.is_valid():
            topping = form.save()

            # Render response for user.
            return HttpResponseRedirect(reverse('example_app_4:topping_detail', args=(topping.pk, )))

    # Handle for non-post request.
    return render(request, 'example_app_4/forms/topping.html', {
        'form': form,
    })


def pizza_create(request):
    """
    Form view for creating a new Pizza.
    """
    form = forms.PizzaForm()

    # Check if request is post.
    if request.method == 'POST':
        form = forms.PizzaForm(request.POST)
        if form.is_valid():
            pizza = form.save()

            # Render response for user.
            return HttpResponseRedirect(reverse('example_app_4:pizza_detail', args=(pizza.pk, )))

    # Handle for non-post request.
    return render(request, 'example_app_4/forms/pizza.html', {
        'form': form,
    })

#endregion Create Views


#region Edit Views

def topping_edit(request, pk):
    """
    Form view for editing a Topping.
    """
    # Pull models from database.
    topping = get_object_or_404(models.Topping, pk=pk)
    form = forms.ToppingForm(instance=topping)

    # Check if request is post.
    if request.method == 'POST':
        form = forms.ToppingForm(instance=topping, data=request.POST)
        if form.is_valid():
            form.save()

            # Render response for user.
            return HttpResponseRedirect(reverse('example_app_4:topping_detail', args=(topping.pk, )))

    # Send to template for user display.
    return render(request, 'example_app_4/forms/topping.html', {
        'form': form,
        'topping': topping,
    })


def pizza_edit(request, pk):
    """
    Form view for editing a Pizza.
    """
    # Pull models from database.
    pizza = get_object_or_404(models.Pizza, pk=pk)
    form = forms.PizzaForm(instance=pizza)

    # Check if request is post.
    if request.method == 'POST':
        form = forms.PizzaForm(instance=pizza, data=request.POST)
        if form.is_valid():
            form.save()

            # Render response for user.
            return HttpResponseRedirect(reverse('example_app_4:pizza_detail', args=(pizza.pk, )))

    # Send to template for user display.
    return render(request, 'example_app_4/forms/pizza.html', {
        'form': form,
        'pizza': pizza,
    })

#endregion Edit Views

example_app_4/templates/example_app_4/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">

  {% block head %}
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      {% block title %}{% endblock title %}

      {% block fonts %}{% endblock fonts %}

      {% block styles %}{% endblock styles %}

      {% block base_scripts %}{% endblock base_scripts %}
    </head>
  {% endblock head %}

  {% block body %}
    <body>
      {% block header %}{% endblock header %}

      <main>{% block content %}{% endblock content %}</main>

      {% block footer %}{% endblock footer %}

      {% block extra_scripts %}{% endblock extra_scripts %}
    </body>
  {% endblock body %}

</html>

example_app_4/templates/example_app_4/index.html
{% extends 'example_app_4/base.html' %}


{% block title%}<title>Example App 4 Index</title>{% endblock title %}


{% block content %}
  <h1>Example App 4 Index</h1>

  <p><a href="{% url 'example_app_4:topping_overview' %}">Toppings</a></p>
  <p><a href="{% url 'example_app_4:pizza_overview' %}">Pizzas</a></p>
{% endblock content %}

example_app_4/templates/example_app_4/pizza_base.html
{% extends 'example_app_4/base.html' %}


{% block title %}<title>Pizza | {%block sub_title %}{% endblock sub_title %}</title>{% endblock title %}


{% block content %}{% endblock content %}

example_app_4/templates/example_app_4/pizza_detail.html
{% extends 'example_app_4/pizza_base.html' %}


{% block sub_title %}Detail{% endblock sub_title %}


{% block content %}
  <h1>Pizza Detail</h1>

  <p>Name: {{ pizza.name }}</p>
  <p>Price: {{ pizza.price }}</p>
  <p>Toppings:
    {% for topping in topping_set %}
      {{ topping.name }},
    {% endfor %}
  </p>
  <p>Created At: {{ pizza.date_created }}</p>
  <p>Last Updated: {{ pizza.date_modified }}</p>

  <p><a href="{% url 'example_app_4:pizza_edit' pk=pizza.pk %}">Edit</a></p>
{% endblock content %}

example_app_4/templates/example_app_4/pizza_overview.html
{% extends 'example_app_4/pizza_base.html' %}


{% block sub_title %}Overview{% endblock sub_title %}


{% block content %}
  <h1>Pizzas</h1>
  <p><a href="{% url 'example_app_4:pizza_create' %}">New</a></p>

  {% for pizza in pizza_list %}
    <li>
      <a href="{% url 'example_app_4:pizza_detail' pk=pizza.pk %}">{{ pizza.name }}</a>
    </li>
  {% endfor %}
{% endblock content %}

example_app_4/templates/example_app_4/topping_base.html
{% extends 'example_app_4/base.html' %}


{% block title %}<title>Topping | {%block sub_title %}{% endblock sub_title %}</title>{% endblock title %}


{% block content %}{% endblock content %}

example_app_4/templates/example_app_4/topping_detail.html
{% extends 'example_app_4/topping_base.html' %}


{% block sub_title %}Detail{% endblock sub_title %}


{% block content %}
  <h1>Topping Detail</h1>

  <p>Name: {{ topping.name }}</p>
  <p>Created At: {{ topping.date_created }}</p>
  <p>Last Updated: {{ topping.date_modified }}</p>

  <p><a href="{% url 'example_app_4:topping_edit' pk=topping.pk %}">Edit</a></p>
{% endblock content %}

example_app_4/templates/example_app_4/topping_overview.html
{% extends 'example_app_4/topping_base.html' %}


{% block sub_title %}Overview{% endblock sub_title %}


{% block content %}
  <h1>Toppings</h1>
  <p><a href="{% url 'example_app_4:topping_create' %}">New</a></p>

  {% for topping in topping_list %}
    <li>
      <a href="{% url 'example_app_4:topping_detail' pk=topping.pk %}">{{ topping.name }}</a>
    </li>
  {% endfor %}
{% endblock content %}